### PR TITLE
v0.79 add support for timeout to IoAdapterPy for URL loading

### PR DESCRIPTION
**Pull request by epeisach**
Add support for specifying an optional time in retrieving data from remote URL services. Defaults to 30 seconds.

### CODE REVIEW

**Comment by piehld** [comment]
Thanks @epeisach. I worry that 30s may be too short. Especially when reading in very large structures over HTTP, which is what we're doing for the weekly update load...

**Review by piehld — CHANGES_REQUESTED** [review]
Change default to 0, to disable timeout. Thanks @epeisach

**Comment by piehld** [comment]
FYI @epeisach, I believe it should be set to `None`, not 0. https://requests.readthedocs.io/en/latest/user/advanced/?highlight=timeout#timeouts

**Comment by epeisach** [comment]
I agree None is the way to go - which is odd - because the Requests documentation indicates float or tuple - never mentioning None - which is what they use.

Tests are running now - but I believe it can be merged.

**Review by piehld — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
