### PR TITLE
V0.88.0 - Add copy method to PdbxContainers for copying entire categories

### PR DESCRIPTION
**Pull request by piehld**

### CODE REVIEW

**Comment by epeisach** [comment]
Three concerns:

a) The docstring should indicate that returns True/False. rename() does not document, but remove() does.  Better to include.
b) If the old name does not exist - returns False  -- which is fine with me.  But what if the new name exists?  Should that be allowed?  Based on my reading of the code, self.append will replace an object of the same name.  I am ok with this situation - and you are too, the docstring should indicate
c) No tests.  A simple test in which a copy operation of category A->B,  and then modification of A should not result in a change in B would be sufficient to me....  Can also test failure case if old name does not exist.

**Comment by piehld** [comment]
Thanks @epeisach, those are great points that I just completely overlooked. I've updated the docstrings (both for copy and replace), added checks for those two cases (trying to copy into an existing name, and trying to copy a non-existent name), and added tests. 

I don't think we should allow the code to overwrite a category if it already exists. It should be up to the user to first delete that destination name, and then copy the new data into it. Or, if you want, we could just add an `overwrite` argument, with default `False`. What do you think?

**Comment by epeisach** [comment]
I am ok with blocking copy to a destination that exists.... As long as it is documented, I am good.

I am a little nervous of changing rename behavior to block if new name exists.... I do not know if it will break anything.

Also - logging at ERROR when destination exists might be wrong. log a WARNING?  I use something like https://sematext.com/blog/logging-levels/ --- not sure at this level if one knows the severity.... If you are relying on the functionality to work - then it is fatal - if not - maybe a warning...

**Comment by piehld** [comment]
@epeisach If you want, I could leave `rename` alone for this PR. But, I do think there is potential for bugs given that it allows for you to overwrite an existing name. For example, the beginning of the rename method works by getting the index of the existing name. Well, if you run it so that you are overwriting an existing name, then there will be two locations in the object list with that new name (one where it originally was, and one where you've replaced the old name with the new name). I think that method needs to be made a little more robust.

I think the ERROR level makes sense though, since we don't want the method to complete running if the requested destination name already exists.

**Comment by epeisach** [comment]
I am look with error on trying to rename to an existing category. Just update HISTORY.txt to indicate change in behavior (or clarify change in behavior) -- in case anyone goes looking.

Then feel free to merge.

**Comment by piehld** [comment]
@epeisach How does this look to you? OK to merge?

**Comment by epeisach** [comment]
Looks good -- merging.

**Pull request merged**
